baseURL = "https://dev.unindented.org"
languageCode = "en-us"
title = "Unindented"
copyright = "All content by <a href=\"https://www.unindented.org/\" rel=\"me\" class=\"h-card\">Daniel Perez Alvarez</a> unless otherwise noted. <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\" target=\"_blank\" rel=\"noreferrer\">Some rights reserved</a>."

enableRobotsTXT = true
ignoreFiles = ["LICENSE", "README.md"]
paginate = 15

[params]
description = "Home of Daniel Perez Alvarez"
themeColor = "#27272a"
backgroundColor = "#27272a"
articleLatestCount = 15
articleRelatedCount = 5
umamiId = "5e64aee0-4350-4ea7-8ee3-6bbad685e225"
umamiTracker = "https://umm.unindented.org/umm.js"

[author]
name = "Daniel Perez Alvarez"
email = "daniel@unindented.org"

[social]
facebook = "unindented"
github = "unindented"
linkedin = "perezalvarez"
mastodon = "hachyderm.io/@unindented"
twitter = "unindented"

# Other stuff

[build]
writeStats = true

[imaging]
hint = 'icon'
quality = 75

[markup.highlight]
noClasses = false

[markup.goldmark.extensions.extras.insert]
enable = true
[markup.goldmark.extensions.extras.mark]
enable = true
[markup.goldmark.extensions.extras.subscript]
enable = true
[markup.goldmark.extensions.extras.superscript]
enable = true

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.goldmark.renderer]
unsafe = true

[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest", "json"]

[outputFormats.manifest]
mediaType = "application/manifest+json"
baseName = "manifest"
isPlainText = true
rel = "manifest"

[outputFormats.rss]
baseName = "rss"

[outputFormats.search]
mediaType = "application/json"
baseName = "search"

[outputs]
home = ["html", "manifest", "rss", "search"]
page = ["html"]
section = ["html"]
taxonomy = ["html"]
term = ["html"]

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = true

[privacy.instagram]
simple = false

[privacy.twitter]
enableDNT = true
simple = false

[privacy.vimeo]
enableDNT = true
simple = false

[privacy.youtube]
privacyEnhanced = true

[related]
includeNewer = true
threshold = 80
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[taxonomies]
tag = "tags"
