name = "Wavey"
license = "MIT"
licenselink = "https://github.com/unindented/unindented-hugo/blob/master/LICENSE"
description = "Wavey theme for my site."
homepage = "https://www.unindented.org/"
tags = []
features = []
min_version = "0.76.0"

[author]
  name = "Daniel Perez Alvarez"
  homepage = "https://www.unindented.org/"
