name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          submodules: recursive
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run lint tests
        run: pnpm test:lint
      - name: Run e2e tests
        run: pnpm test:e2e
      - name: Build
        run: |
          pnpm build \
            --baseURL "$BASE_URL" \
            --destination "public"
          cp static/.* public/
        env:
          BASE_URL: ${{ github.event_name == 'pull_request' && 'https://dev.unindented.org/' || 'https://www.unindented.org/' }}
      - name: Run Lighthouse tests
        run: pnpm test:lhci
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Upload website
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: website
          path: public
          retention-days: 1
          include-hidden-files: true
      - name: Upload e2e test reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ always() }}
        with:
          name: e2e-reports
          path: |
            e2e-report/
            e2e-results/
          retention-days: 7
