name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          submodules: recursive
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run lint tests
        run: pnpm test:lint
      - name: Run e2e tests
        run: pnpm test:e2e
      - name: Build
        run: |
          pnpm build \
            --baseURL "$BASE_URL" \
            --destination "public"
        env:
          BASE_URL: ${{ github.event_name == 'pull_request' && 'https://dev.unindented.org/' || 'https://www.unindented.org/' }}
      - name: Run Lighthouse tests
        run: pnpm test:lhci
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Upload website
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: website
          path: public
          retention-days: 1
      - name: Upload e2e test reports
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        if: ${{ always() }}
        with:
          name: e2e-reports
          path: |
            e2e-report/
            e2e-results/
          retention-days: 7
