name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: read
  deployments: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          submodules: recursive
      - name: Download website
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: website
          path: public
      - name: Deploy
        uses: ./.github/actions/rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          options: --archive --delete --exclude-from .rsyncignore
          source: public
          target: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }}:~/${{ github.event_name == 'pull_request' && 'dev.unindented.org' || 'unindented.org' }}/
